/**
 * @format
 * Home Style
 */

import {ScaledSheet} from 'react-native-size-matters';
import {Colors} from '@app/constants';

export const getStyle = () => {
  return ScaledSheet.create({
    container: {
      flex: 1,
      backgroundColor: Colors.Black,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: '30@ms',
    },
    containerDetail: {
      flexGrow: 1,
      backgroundColor: Colors.Black,
      paddingHorizontal: '30@ms',
      borderTopRightRadius: 40,
      borderTopLeftRadius: 40,
    },
    content: {
      fontSize: '18@ms',
      textAlign: 'center',
      color: 'grey',
    },

    emptyContainer: {
      alignItems: 'center',
    },
    listHeaderContainer: {
      borderWidth: 2,
      borderTopColor: '#D8D8D8',
      borderBottomColor: '#D8D8D8',
      justifyContent: 'center',
      alignItems: 'center',
      height: '40@ms',
    },
    listHeader: {
      fontSize: 20,
      fontWeight: 'bold',
    },
    seprateList: {
      height: 2,
      backgroundColor: '#D8D8D8',
      marginHorizontal: 7,
    },
    detailContainer: {
      flexDirection: 'row',
      marginVertical: '15@ms',
      marginHorizontal: '15@ms',
    },
    categoryContainer: {
      borderColor: Colors.Primary,
      borderWidth: 5,
      borderRadius: '20@ms',
      margin: '25@ms',
      // padding: '5@ms',
      overflow: 'hidden',
    },

    imageCat: {
      width: '120@ms',
      height: '120@ms',
      resizeMode: 'cover',
    },

    imageDetails: {
      width: '170@ms',
      height: '170@ms',
    },
    contentContainer: {
      flex: '4@ms',
      borderColor: 'lightgray',
      borderBottomWidth: 0.5,
      justifyContent: 'center',
      marginHorizontal: '10@ms',
    },
    contentCatContainer: {
      alignItems: 'center',
      paddingVertical: '10@ms',
      fontWeight: 500,
      backgroundColor: Colors.Primary,
    },
    title: {
      fontSize: '18@ms',
      fontWeight: '500',
      color: Colors.White,
    },
    listEmpty: {
      // flex:1,
      justifyContent: 'center',
      alignItems: 'center',
      resizeMode: 'cover',
    },
    heartContainer: {
      justifyContent: 'center',
    },
    detailTitle: {
      fontSize: '25@ms',
      fontWeight: '600',
      color: Colors.White,
      paddingVertical: '20@ms',
    },
    detailDiscription: {
      fontSize: '13@ms',
      fontWeight: '400',
      color: Colors.White,
    },
    containerStyle: {
      flex: 1,
      height: '120@ms',
      width: '100%',
      marginVertical: '15@ms',
      paddingVertical: '10@ms',
    },

    textStyle: {
      color: Colors.White,
    },
    customRatingBarStyle: {
      flexDirection: 'row',
      marginVertical: '3@ms',
    },
    starImageStyle: {
      width: 40,
      height: 40,
      resizeMode: 'cover',
    },
    authorContainer: {
      paddingVertical: '10@ms',
    },
    authorImg: {
      width: '30@ms',
      height: '30@ms',
      borderRadius: 50,
    },
    authorHead: {
      color: Colors.White,
      paddingTop: '7@ms',
      paddingHorizontal: '10@ms',
    },
    authorName: {
      color: 'gray',
      paddingHorizontal: '10@ms',
    },
    lineStyle: {
      borderWidth: 0.3,
      borderColor: Colors.White,
      margin: '10@ms',
    },
    chaptersTitle: {
      fontSize: '20@ms',
      fontWeight: '600',
      color: Colors.White,
      paddingVertical: '10@ms',
    },
    chaptersContent: {
      fontSize: '15@ms',
      fontWeight: '400',
      color: Colors.Primary,
    },
    chaptersSubTitle: {
      fontSize: '12@ms',
      fontWeight: '400',
      color: Colors.White,
      paddingVertical: '2@ms',
      paddingHorizontal: '5@ms',
    },
    textStyle: {
      textAlign: 'center',
      fontSize: '17@ms',
      color: Colors.White,
      marginVertical: '7@ms',
      marginHorizontal: '7@ms',
    },
    topTabContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: '15@ms',
      paddingVertical: '5@ms',
      margin: '2@ms',
      borderWidth: '1@ms',
      borderColor: Colors.Primary,
      borderRadius: '15@ms',
    },
    activeTabContainer: {
      backgroundColor: Colors.Primary,
    },
    topTabTitle: {
      textAlign: 'center',
      fontSize: '17@ms',
      color: Colors.Primary,
      fontWeight: '600',
    },
    activeTabTitle: {
      color: Colors.White,
    },
    modalContainer: {
      alignItems: 'center',
      height: '150@ms',
      borderRadius: '15@ms',
    },
    imageModal: {
      width: '70@ms',
      height: '70@ms',
    },
    modalContent: {
      fontSize: '16@ms',
      fontWeight: '600',
      color: Colors.Primary,
      paddingVertical: '5@ms',
    },

    trackProgress: {
      marginTop: '40@ms',
      textAlign: 'center',
      fontSize: '24@ms',
      color: '#eee',
    },
    songTitle: {
      fontSize: '32@ms',
      marginTop: '50@ms',
      color: '#ccc',
    },
    artistName: {
      fontSize: '24@ms',
      color: '#888',
    },

    // ......hhh
    dropdown: {
      flex: 1,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'column',
    },
    dropdownadd: {
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'column',
      marginTop: '20@ms',
    },
    button: {
      flexDirection: 'row',
      alignItems: 'center',
      borderColor: Colors.Orange,
      borderWidth: 1.5,
      height: 50,
      width: '100%',
      borderRadius: 10,
    },
    buttonText: {
      flex: 1,
      textAlign: 'center',
      color: Colors.Orange,
      fontWeight: 'bold',
      fontSize: 15,
    },
    icon: {
      marginRight: 10,
      color: Colors.White,
    },
    transactionContainer: {
      flexDirection: 'row',
      // marginHorizontal: '10@ms',
      marginVertical: '10@ms',
    },
    transactionHeader: {
      color: Colors.Black,
      fontWeight: 600,
      fontSize: '18@ms',
    },
    viewAllContainer: {
      position: 'absolute',
      right: '0@ms',
    },
    viewAllContent: {
      color: Colors.Gray,
      fontWeight: 600,
      fontSize: '10@ms',
    },
    transactionsList: {
      flexDirection: 'row',
      borderRadius: '10@ms',
      backgroundColor: Colors.Gray,
      marginVertical: '5@ms',
      height: '45@ms',
      alignItems: 'center',
      padding: '10@ms',
    },
    image: {
      width: '30@ms',
      height: '30@ms',
      borderRadius: '60@ms',
    },
    titleContainer: {
      paddingHorizontal: '10@ms',
    },
    titleLabel: {
      fontSize: '13@ms',
      color: Colors.Black,
      fontWeight: 600,
    },
    titleAccount: {
      fontSize: '10@ms',
      color: '#808080',
      fontWeight: 'bold',
    },
    paymentContainer: {
      position: 'absolute',
      right: '10@ms',
      // paddingHorizontal: '10@ms',
    },
    price: {
      fontSize: '15@ms',
      color: Colors.Green,
      fontWeight: 'bold',
    },
    graphStyle: {
      flex: 1,
      paddingRight: '25@ms',
      marginVertical: '15@ms',
    },
    // Expense
    calenderContainer: {
      backgroundColor: Colors.Gray,
      // marginHorizontal: '10@ms',
      marginVertical: '10@ms',
      borderRadius: '10@ms',
    },
    storeContainer: {
      width: '87%',
      // marginHorizontal: '30@ms',
      borderRadius: '10@ms',
      backgroundColor: Colors.Gray,
      marginVertical: '5@ms',
      height: '145@ms',
      padding: '10@ms',
    },
    storeDetails: {
      flexDirection: 'row',
    },
    storeTotal: {
      fontSize: '15@ms',
      color: '#808080',
      fontWeight: 'bold',
      marginTop: '25@ms',
      marginHorizontal: '10@ms',
    },
    priceTotal: {
      fontSize: '15@ms',
      color: Colors.Green,
      fontWeight: 'bold',
      marginVertical: '10@ms',
      marginHorizontal: '10@ms',
    },
    perRatio: {position: 'absolute', right: 10},
    ammountContainer: {
      flexDirection: 'row',
      marginTop: '15@ms',
    },
    balenceContainer: {
      backgroundColor: Colors.Purple,
      marginVertical: '10@ms',
      // marginHorizontal: '10@ms',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: '15@ms',
      width: '162@ms',
      height: '100@ms',
      borderRadius: '5@ms',
    },
    totBal: {
      color: Colors.White,
      fontSize: '12@ms',
      // fontWeight: 'bold',
    },
    totPrice: {
      color: Colors.White,
      fontSize: '25@ms',
      fontWeight: 'bold',
    },
    balenceBottomContainer: {
      backgroundColor: Colors.Gray,
      marginVertical: '10@ms',
      marginHorizontal: '10@ms',
      alignItems: 'center',
      paddingHorizontal: '15@ms',
      width: '162@ms',
      height: '40@ms',
      borderRadius: '5@ms',
      flexDirection: 'row',
      marginTop: '-25@ms',
    },
    monthSpendContainer: {
      // marginHorizontal: '10@ms',
    },
    // Wallet
    walletContainer: {
      marginHorizontal: '10@ms',
      marginVertical: '10@ms',
    },
    priceContainer: {
      backgroundColor: Colors.Purple,
      height: '130@ms',
      borderRadius: '30@ms',
      width: '100%',
      justifyContent: 'center',
      paddingHorizontal: '25@ms',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 0.3},
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 10,
    },
    priceLabel: {
      color: Colors.Gray,
      fontSize: '20@ms',
    },
    addCashBtn: {
      backgroundColor: Colors.Orange,
      width: '100@ms',
      height: '30@ms',
      borderRadius: '15@ms',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'absolute',
      right: '20@ms',
      shadowColor: '#fff',
      shadowOffset: {width: 0, height: 0.3},
      shadowOpacity: 0.3,
      shadowRadius: 3,
      elevation: 20,
    },
    addCashLabel: {
      color: Colors.White,
      fontWeight: 'bold',
    },
    listItem: {
      backgroundColor: Colors.Purple,
      width: 35,
      height: 35,
      borderRadius: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    dayStatus: {
      color: Colors.GrayDark,
      fontSize: '10@ms',
      marginHorizontal: '10@ms',
      marginVertical: '5@ms',
    },
    // AddCash
    head: {
      height: '70@ms',
      backgroundColor: Colors.White,
    },
    headerTitle: {
      fontWeight: 'bold',
      color: Colors.Black,
      textAlign: 'center',
      fontSize: '15@ms',
    },
    addCash: {
      marginHorizontal: '10@ms',
      marginVertical: '10@ms',
    },
    modalText: {
      color: Colors.White,
      fontWeight: 'bold',
      fontSize: '20@ms',
    },
    termscondition: {
      position: 'absolute',
      bottom: 360,
      left: 25,
      flexDirection: 'row',
    },
    termsconditionContent: {
      fontSize: '12@ms',
      color: Colors.Orange,
      marginHorizontal: '10@ms',
      textDecorationLine: 'underline',
    },
    containerModalStyle: {
      backgroundColor: Colors.White,
      // padding: '20@ms',
    },
    name: {
      width: '100%',
      color: Colors.Black,
      fontSize: '18@ms',
      marginTop: '3@ms',
      fontWeight: '700',
    },
    email: {
      width: '100%',
      color: Colors.Black,
      fontSize: '16@ms',
      marginTop: '3@ms',
    },
    containerStyle: {
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: '10@ms',
    },
    modalHeaderContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.Orange,
      width: '100%',
      height: '42@ms',
      flexDirection: 'row',
    },
    modalHeader: {
      fontSize: '20@ms',
      fontWeight: '700',
      color: Colors.White,
      fontFamily: 'Poppins',
      paddingLeft: '10@ms',
    },
    modalCrown: {
      width: '25@ms',
      height: '17@ms',
    },
    closeIcon: {
      position: 'absolute',
      right: '0@ms',
      top: '0@ms',
      zIndex: 1,
      padding: '20@ms',
    },
    details: {
      fontSize: '12@ms',
      // fontWeight: '700',
      color: Colors.Black,
      fontFamily: 'Poppins',
      lineHeight: 18,
      maxWidth: '230@ms',
    },
    rightIcon: {
      margin: '20@ms',
      marginBottom: '0@ms',
    },
    checkIcon: {
      color: Colors.Orange,
      fontSize: '20@ms',
      width: '15%',
    },
    memberContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      width: '100%',
    },
    memberBtn2: {
      borderColor: Colors.Orange,
      borderWidth: '2@ms',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: '2@ms',
      height: '35@ms',
      width: '160@ms',
      margin: '5@ms',
    },
    memberBtnText2: {
      fontSize: '12@ms',
      fontWeight: '700',
      color: Colors.Black,
      fontFamily: 'Poppins',
      lineHeight: 18,
    },
    memberBtn: {
      // borderColor: Colors.Orange,
      // borderWidth: '2@ms',
      // justifyContent: 'center',
      // alignItems: 'center',
      borderRadius: '5@ms',
      // height: '65@ms',
      width: '100%',
      margin: '4@ms',
    },
    memberBtnText: {
      fontSize: '12@ms',
      fontWeight: '700',
      color: '#fff',
      fontFamily: 'Poppins',
      lineHeight: 18,
    },
    modalHeaderView: {
      backgroundColor: Colors.Orange,
      height: '42@ms',
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkContainerStyle: {
      height: '43@ms',
    },
    textStyle: {
      height: '43@ms',
    },
    paymentDetail: {
      fontSize: '11@ms',
      fontWeight: '700',
      color: Colors.Black,
      fontFamily: 'Poppins',
      lineHeight: 16,
      margin: '10@ms',
      marginLeft: '30@ms',
      width: '50%',
      // textAlign:'center'
    },
    offerTittle: {
      fontSize: '16@ms',
      fontWeight: '700',
    },
    profile: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: '10@ms',
      justifyContent: 'center',
      marginTop: '10@ms',
      marginBottom: '10@ms',
    },
    userImageContainer: {
      width: '86@ms',
      height: '86@ms',
      justifyContent: 'center',
      alignItems: 'center',
      margin: '5@ms',
    },
    userImage: {
      width: '80@ms',
      height: '80@ms',
      borderRadius: '40@ms',
      resizeMode: 'contain',
      borderWidth: '3@ms',
      borderColor: '#FFBC13',
    },
    userCrownContainer: {
      position: 'absolute',
      zIndex: 1,
      bottom: '10@ms',
      left: '2@ms',
      backgroundColor: '#000',
      borderRadius: '50@ms',
      width: '25@ms',
      height: '25@ms',
      justifyContent: 'center',
      alignItems: 'center',
    },
    userCrown: {
      width: '15@ms',
      height: '12@ms',
      borderRadius: '12.5@ms',
      // resizeMode: 'contain',
    },
    userDetailContainer: {
      // flex: 1,
      maxWidth: '100@ms',
    },
    editIcon: {
      marginTop: '0@ms',
      marginLeft: '15@ms',
    },
    loaderContainer: {
      position: 'absolute',
      backgroundColor: Colors.White,
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      opacity: 0.6,
    },
    containerStyle: {
      height: '90@ms',
      marginTop: '25@ms',
      maxWidth: '90%',
      alignSelf: 'center',
    },
    headingTittle: {
      marginTop: '10@ms',
      marginBottom: '4@ms',
      padding: '10@ms',
      textAlign: 'center',
    },
    vehicleModalContent: {
      backgroundColor: Colors.White,
      paddingVertical: '20@ms',
    },
    vehicleModalHeaderContainer: {
      backgroundColor: Colors.Orange,
      height: '53@ms',
      justifyContent: 'center',
      marginBottom: '26@ms',
    },
    vehicleModalHeader: {
      fontSize: '16@ms',
      fontWeight: '600',
      color: Colors.White,
      fontFamily: 'Poppins',
    },
    vehicleModalContentContainer: {
      width: '100%',
      paddingHorizontal: '26@ms',
    },
    addVechileNumber: {
      marginTop: '20@ms',
    },
    checkboxContainer: {
      flexDirection: 'row',
      width: '100%',
    },
    labelHead: {
      marginTop: '5@ms',
      fontSize: '12@ms',
      color: Colors.Black,
    },
    labelText: {
      color: Colors.Orange,
      fontSize: '13@ms',
      fontFamily: 'Poppins',
    },
    vehicleInputLabel: {
      width: '100%',
      color: Colors.Black,
      fontSize: '14@ms',
      fontWeight: '400',
      fontFamily: 'Poppins',
    },
    planContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      borderColor: Colors.Orange,
      borderWidth: '1@ms',
      borderRadius: '10@ms',
      marginTop: '10@ms',
      marginBottom: '10@ms',
      padding: '10@ms',
      margin: '20@ms',
    },
    centeredView: {
      flex: 1,
      justifyContent: 'center',
      marginTop: '322@ms',
      marginLeft: '18@ms',
      width: '90%',
    },
    modalView: {
      backgroundColor: 'white',
      borderRadius: 10,
      shadowColor: Colors.Black,
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      padding: '6@ms',
      fontSize: '12@ms',
      fontFamily: 'Poppins',
      elevation: 5,
    },
    closeContainer: {
      position: 'absolute',
      top: -7,
      right: -7,
      zIndex: 10,
    },
    close: {
      backgroundColor: Colors.Orange,
      borderRadius: '50@ms',
      width: '20@ms',
      height: '20@ms',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      height: '200@ms',
    },
    modalText: {
      padding: '10@ms',
      fontSize: '12@ms',
      width: '100%',
    },
    popupContainer: {
      backgroundColor: Colors.White,
      width: '280@ms',
      minHeight: '85@ms',
      alignSelf: 'center',
      borderRadius: 5,
      elevation: 25,
      shadowColor: Colors.Black,
      padding: 10,
      position: 'absolute',
    },
    cardStyle: {
      width: '100%',
      height: '50@ms',
      marginVertical: '30@ms',
      borderWidth: 1,
    },
    modalContentContainer: {
      paddingBottom: '30@ms',
      flex: 1,
    },

    details: {
      color: Colors.Black,
      fontSize: '13@ms',
      fontWeight: '400',
      fontFamily: 'Poppins',
      marginTop: '40@ms',
      marginBottom: '40@ms',
    },
    btnLabel: {
      color: Colors.White,
      fontSize: '16@ms',
      fontWeight: '700',
      fontFamily: 'Poppins',
    },
    welcomeContainer: {
      width: '100%',
      backgroundColor: Colors.White,
      alignSelf: 'center',
      margin: '15@ms',
    },
    welcomeHeading: {
      justifyContent: 'center',
      alignItems: 'center',
      // flexDirection: 'row',
      marginBottom: '15@ms',
    },
    welcomeName: {
      color: Colors.Black,
      fontSize: '17@ms',
      fontWeight: '700',
      fontFamily: 'Poppins',
    },
    greetingMsg: {
      color: Colors.Orange,
      fontSize: '17@ms',
      fontWeight: '700',
      fontFamily: 'Poppins',
      textAlign: 'center',
      textTransform: 'capitalize',
    },
    planDetailHeading: {
      fontWeight: 'bold',
    },
    planDetailContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      width: '100%',
      paddingHorizontal: '15@ms',
      marginBottom: '15@ms',
    },
    amountAdd: {
      color: Colors.Black,
      fontSize: '20@ms',
      marginHorizontal: '20@ms',
      fontWeight: 'bold',
    },
    transactionDetails: {
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.Orange,
      height: '90%',
      borderRadius: '10@ms',
    },
    transactionTitle: {
      color: Colors.White,
      fontWeight: 'bold',
      fontSize: '20@ms',
    },
    text: {
      fontSize: '15@ms',
      color: Colors.Black,
      padding: '3@ms',
      marginBottom: '10@ms',
      paddingHorizontal: '10@ms',
      marginTop: '10@ms',
    },
    datepickerContainer: {
      flexDirection: 'row',
      height: '48@ms',
      width: '100%',
      borderColor: '#CECECE',
      borderWidth: '1.5@ms',
      marginBottom: '10@ms',
      borderRadius: '5@ms',
      marginVertical: '10@ms',
      marginBottom: '20@ms',
    },
  });
};
